# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4039036db5b538d8fe3a4843ffbd7e129457580f8f5e8af09f043357cb0314fe41e8a3bda671c8116bd2d99c9290d2e5ce25b3d7179261474ad46af79621aab2

test:
  secret_key_base: dbbc4967f34af22b24c19d1c4f7ae5492e0a56331e58305c85923c470c6ecfe97e1e10f78d5cf06dde53c3396bdd43235825bcc8920618eb8a8f0829e4a7ee89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
